FROM ubuntu:16.04
LABEL maintainer <Harit Kumar>

COPY gnatsd /gnatsd
COPY gnatsd.conf gnatsd.conf

# Expose client, management, and cluster ports
EXPOSE 4222 8222 6222
RUN chmod +x /gnatsd

# Run via the configuration file
ENTRYPOINT ["/gnatsd"]
CMD ["-c", "gnatsd.conf"]